### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by thedavidmarkovich** [dblock/slack-amber-alert#2]
"Thanks for installing Missing Kids Bot - you're doing your part in helping out. 
When somebody goes missing we'll push the info to this channel. "

**Comment by dblock** [comment]
Done. 
<img width="678" alt="screen shot 2016-04-30 at 10 43 04 am" src="https://cloud.githubusercontent.com/assets/542335/14936664/5cc86d5c-0ec0-11e6-9e15-6856c6d462eb.png">
